const electronConnector = {
    systemAction: (action) => window.electronAPI.systemAction(action),
    nintendoSearch: (data) => window.electronAPI.nintendoSearch(data),
    nintendoReq: (data) => window.electronAPI.nintendoReq(data),
    openFile: (data) => window.electronAPI.openFile(data),
    getFile: (data) => window.electronAPI.getFile(data),
    getEgsId: (d) => window.electronAPI.getEgsId(d),
    getImage: (data) => window.electronAPI.getImage(data),
    getSteamData: (data) => window.electronAPI.getSteamData(data),
    getFolder: (data) => window.electronAPI.getFolder(data),
    steamSearch: (data) => window.electronAPI.steamSearch(data),
    steamgriddbSearch: (data) => window.electronAPI.steamgriddbSearch(data),
    getSteamAchievements: (data) => window.electronAPI.getSteamAchievements(data),
    readFile: (data) => window.electronAPI.readFile(data),
    onVisibilityChange: (data) => window.electronAPI.onVisibilityChange(data),
    gameStatus: (data) => window.electronAPI.gameStatus(data),
    lastModify: (data) => window.electronAPI.lastModify(data),
    restartPC: () => window.electronAPI.restartPC(),
    rpcs3: (data) => window.electronAPI.rpcs3(data),
    getGamesRPCS3: (data) => window.electronAPI.getGamesRPCS3(data),
    crackWatchRequest: (data) => window.electronAPI.crackWatchRequest(data),
    nintendoData: (url) => window.electronAPI.nintendoData(url),
    getFreeGames: (data) => window.electronAPI.getFreeGames(data),
    saveImage: (data) => window.electronAPI.saveImage(data),
    openLink: (url) => window.electronAPI.openLink(url),
    getEpicGamesAchievements: (data) => window.electronAPI.getEpicGamesAchievements(data),
    changeTheme: (data) => window.electronAPI.changeTheme(data),
    getPlayerProfileAchievementsByProductId: (data) => window.electronAPI.getPlayerProfileAchievementsByProductId(data),
    watchFile: (data) => window.electronAPI.watchFile(data),
    stopWatch: (data) => window.electronAPI.stopWatch(data),
    fileChanged: (data) => window.electronAPI.fileChanged(data),
    sendNotification: (data) => window.electronAPI.sendNotification(data),
    downloadAudio: (data) => window.electronAPI.downloadAudio(data),
    howLongToBeat: (querystring) => window.electronAPI.howLongToBeat(querystring)
};

export default electronConnector;